In [2]:
import tensorflow as tf
import numpy as np

# 1. 用numpy来创建numpy

In [7]:
a = tf.convert_to_tensor(np.ones([2,3]))#以下两种都是利用numpy来创建tensor
a

<tf.Tensor: id=3, shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [10]:
a = tf.convert_to_tensor(np.zeros([3,4]))#最好是把float64转化为float32，不然后续的运算容易报错
a

<tf.Tensor: id=4, shape=(3, 4), dtype=float64, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])>

In [11]:
a = tf.convert_to_tensor([1,2.])#输入有浮点型会转换成都为浮点型
a

<tf.Tensor: id=5, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

## 2. 直接用tf里面的函数 zeros、ones、fill来创建tensor

In [15]:
a= tf.zeros([])#直接用zeros创建，这里的[]是shape，空代表为一个标量
a

<tf.Tensor: id=14, shape=(), dtype=float32, numpy=0.0>

In [16]:
b = tf.zeros([1])#一维的向量
b

<tf.Tensor: id=17, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [17]:
c = tf.zeros([2,3])#shape为[2，3]
c

<tf.Tensor: id=20, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [19]:
d = tf.zeros_like(c)#创建一个与c相同shape的矩阵
d

<tf.Tensor: id=22, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
a = tf.ones(1)#用ones创建全为1的tensor，用法完全与zeros一致
a

<tf.Tensor: id=25, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [21]:
b = tf.ones([2,2])
b

<tf.Tensor: id=28, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [22]:
c = tf.fill([2,2],8)#fill前面表示shape后面表示要填充的内容
c

<tf.Tensor: id=31, shape=(2, 2), dtype=int32, numpy=
array([[8, 8],
       [8, 8]])>

## 3. 用random创建随机分布的tensor

In [24]:
a = tf.random.normal([2,2],mean = 2,stddev=1)#创建的正态分布
a

<tf.Tensor: id=43, shape=(2, 2), dtype=float32, numpy=
array([[0.6689582, 0.9684888],
       [1.743693 , 2.1757522]], dtype=float32)>

In [26]:
a = tf.random.normal([2,2])#不另外设置mean和stddev的话默认是[0,1]的标准正态分布
a

<tf.Tensor: id=49, shape=(2, 2), dtype=float32, numpy=
array([[ 1.0872152 , -0.6914426 ],
       [-1.616489  ,  0.78221744]], dtype=float32)>

In [27]:
a = tf.random.truncated_normal([2,2])#截断的正态分布，比较适合对于神经网络求导里面将gradient vanish 的部分截断
a

<tf.Tensor: id=55, shape=(2, 2), dtype=float32, numpy=
array([[-1.1537383 , -0.01671567],
       [ 1.578387  ,  1.3195207 ]], dtype=float32)>

In [28]:
a = tf.random.uniform([2,2],minval=1,maxval=100)#创建均匀分布，自己可以设置边值
a

<tf.Tensor: id=62, shape=(2, 2), dtype=float32, numpy=
array([[68.99183 , 36.488396],
       [84.47099 , 97.10027 ]], dtype=float32)>

## 4.constant创建

In [46]:
a = tf.constant(1)
a

<tf.Tensor: id=98, shape=(), dtype=int32, numpy=1>

In [47]:
b = tf.constant([2,3])
b

<tf.Tensor: id=99, shape=(2,), dtype=int32, numpy=array([2, 3])>

## 5.实战打乱生成数据的顺序

In [29]:
idx = tf.range(10)
idx

<tf.Tensor: id=66, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [31]:
idx = tf.random.shuffle(idx)#随机打散
idx

<tf.Tensor: id=68, shape=(10,), dtype=int32, numpy=array([8, 5, 6, 7, 4, 1, 3, 0, 2, 9])>

In [33]:
a = tf.random.normal([10])
a

<tf.Tensor: id=77, shape=(10,), dtype=float32, numpy=
array([-0.0041074 , -0.23370358, -0.4972246 ,  1.5317067 , -0.0339614 ,
       -0.55023056, -1.228694  , -1.2933594 ,  0.40706202,  0.32445982],
      dtype=float32)>

In [34]:
a = tf.gather(a,idx)#将随机打散的索引一一对应之后按打散后的随机索引排列
a

<tf.Tensor: id=79, shape=(10,), dtype=float32, numpy=
array([ 0.40706202, -0.55023056, -1.228694  , -1.2933594 , -0.0339614 ,
       -0.23370358,  1.5317067 , -0.0041074 , -0.4972246 ,  0.32445982],
      dtype=float32)>

In [43]:
b = tf.random.uniform([10],maxval=10,dtype = tf.int32)
b

<tf.Tensor: id=94, shape=(10,), dtype=int32, numpy=array([2, 0, 4, 7, 0, 5, 9, 7, 9, 8])>

In [44]:
b = tf.gather(b,idx)
b

<tf.Tensor: id=96, shape=(10,), dtype=int32, numpy=array([9, 5, 9, 7, 0, 0, 7, 2, 4, 8])>

## 6.理解各数据类型在神经网络上的意义
## scalar代表标量，常见的有loss、accuracy

In [49]:
a = tf.random.uniform([4,10])#随机生成一个矩阵模拟图片的相素点
a

<tf.Tensor: id=113, shape=(4, 10), dtype=float32, numpy=
array([[0.04911613, 0.85736096, 0.99797094, 0.5779793 , 0.04328454,
        0.46136248, 0.25015116, 0.40377474, 0.31327343, 0.70316255],
       [0.45146453, 0.23739791, 0.9366081 , 0.16303086, 0.5381291 ,
        0.65859294, 0.8648814 , 0.9026607 , 0.51495254, 0.39204645],
       [0.04109395, 0.46101546, 0.743227  , 0.4685731 , 0.04220283,
        0.75863147, 0.23850048, 0.7974751 , 0.842901  , 0.60330164],
       [0.9342786 , 0.9352094 , 0.3686353 , 0.07728219, 0.02064884,
        0.47484708, 0.85366607, 0.4837011 , 0.85385716, 0.9596369 ]],
      dtype=float32)>

In [51]:
b = tf.range(4)
b = tf.one_hot(b,depth = 10)
b

<tf.Tensor: id=125, shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [52]:
loss = tf.keras.losses.mse(b,a)#现成函数 mse 计算求和（b-a）^2，即欧拉距离，再求均值，计算预测值与实际值的loss
loss

<tf.Tensor: id=128, shape=(4,), dtype=float32, numpy=array([0.40021706, 0.4394216 , 0.28443238, 0.5573387 ], dtype=float32)>

In [54]:
loss = tf.reduce_mean(loss)#shape=()即代表标量
loss

<tf.Tensor: id=130, shape=(), dtype=float32, numpy=0.42035246>

## 7.vector在神经网络里面常用 bias
## bias一般是与输出的类别相一致的向量[out_dim]

## 8.matrix在神经网络里面常用的是input[b,vec_dim]、w[input_dim,out_dim]

## 9.tensor 三维表示文本
## 10.tensor 表示 图像