# 张量排序

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([7,4,2,1,8,3,6,9])
a

<tf.Tensor: id=0, shape=(8,), dtype=int32, numpy=array([7, 4, 2, 1, 8, 3, 6, 9])>

## 1.sort直接排序，默认从小到大，也可以通过direction来设置方式

In [3]:
tf.sort(a)

<tf.Tensor: id=11, shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 6, 7, 8, 9])>

In [5]:
tf.sort(a,direction = 'DESCENDING')

<tf.Tensor: id=19, shape=(8,), dtype=int32, numpy=array([9, 8, 7, 6, 4, 3, 2, 1])>

## 2.argsort是返回排序的索引号，同样的用法

In [6]:
tf.argsort(a)

<tf.Tensor: id=30, shape=(8,), dtype=int32, numpy=array([3, 2, 5, 1, 6, 0, 4, 7])>

In [7]:
tf.argsort(a,direction = 'DESCENDING')

<tf.Tensor: id=39, shape=(8,), dtype=int32, numpy=array([7, 4, 0, 6, 1, 5, 2, 3])>

In [11]:
b = tf.random.uniform([4,5],maxval = 10,dtype = tf.int32)
b

<tf.Tensor: id=57, shape=(4, 5), dtype=int32, numpy=
array([[8, 4, 7, 9, 0],
       [1, 7, 0, 8, 8],
       [9, 8, 2, 1, 0],
       [7, 4, 6, 4, 0]])>

In [12]:
tf.sort(b)

<tf.Tensor: id=68, shape=(4, 5), dtype=int32, numpy=
array([[0, 4, 7, 8, 9],
       [0, 1, 7, 8, 8],
       [0, 1, 2, 8, 9],
       [0, 4, 4, 6, 7]])>

In [14]:
tf.sort(b,direction = 'DESCENDING')

<tf.Tensor: id=85, shape=(4, 5), dtype=int32, numpy=
array([[9, 8, 7, 4, 0],
       [8, 8, 7, 1, 0],
       [9, 8, 2, 1, 0],
       [7, 6, 4, 4, 0]])>

In [19]:
c = tf.argsort(b)
c

<tf.Tensor: id=139, shape=(4, 5), dtype=int32, numpy=
array([[4, 1, 2, 0, 3],
       [2, 0, 1, 3, 4],
       [4, 3, 2, 1, 0],
       [4, 1, 3, 2, 0]])>

In [24]:
a = tf.random.shuffle(tf.range(8))
a

<tf.Tensor: id=182, shape=(8,), dtype=int32, numpy=array([5, 0, 7, 3, 1, 4, 6, 2])>

In [28]:
idx = tf.argsort(a)
idx

<tf.Tensor: id=217, shape=(8,), dtype=int32, numpy=array([1, 4, 7, 3, 5, 0, 6, 2])>

In [29]:
tf.gather(a,idx)

<tf.Tensor: id=219, shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7])>

## 3. 当不需要全部排列时，top_k,只输出前面k个排序（索引）

In [32]:
a = tf.random.uniform([3,3],maxval=9,dtype = tf.int32)
a

<tf.Tensor: id=230, shape=(3, 3), dtype=int32, numpy=
array([[2, 2, 1],
       [0, 8, 4],
       [1, 8, 6]])>

In [34]:
res = tf.math.top_k(a,2)

## top_k会返回两个值，分别时indices和values

In [35]:
res[0]

<tf.Tensor: id=232, shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [8, 4],
       [8, 6]])>

In [36]:
res[1]

<tf.Tensor: id=233, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [1, 2]])>

In [37]:
res.indices

<tf.Tensor: id=233, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [1, 2]])>

In [39]:
res.values

<tf.Tensor: id=232, shape=(3, 2), dtype=int32, numpy=
array([[2, 2],
       [8, 4],
       [8, 6]])>

## 4.top_k的最常用是实现前几项预测的正确率的计算

In [40]:
pro = tf.constant([[0.1,0.7,0.2],[0.4,0.1,0.5]])
pro

<tf.Tensor: id=234, shape=(2, 3), dtype=float32, numpy=
array([[0.1, 0.7, 0.2],
       [0.4, 0.1, 0.5]], dtype=float32)>

In [42]:
target = tf.constant([2,0])

In [45]:
k_b = tf.math.top_k(pro,3).indices
k_b

<tf.Tensor: id=243, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [2, 0, 1]])>

In [46]:
k_b = tf.transpose(k_b)
k_b

<tf.Tensor: id=245, shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 0],
       [0, 1]])>

In [48]:
target = tf.broadcast_to(target,[3,2])
target

<tf.Tensor: id=249, shape=(3, 2), dtype=int32, numpy=
array([[2, 0],
       [2, 0],
       [2, 0]])>

In [50]:
correct = tf.equal(k_b,target)
correct

<tf.Tensor: id=251, shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [ True,  True],
       [False, False]])>

In [52]:
tf.cast(correct,dtype = tf.int32)

<tf.Tensor: id=252, shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 1],
       [0, 0]])>