# 填充与复制

In [1]:
import tensorflow as tf

In [3]:
a = tf.constant([1,3,2,4,5])
a

<tf.Tensor: id=0, shape=(5,), dtype=int32, numpy=array([1, 3, 2, 4, 5])>

## 1.pad对于一维来讲，只有前后，对于二维有上下左右四个位置，用方括号放在一起

In [7]:
b = tf.pad(a,[[3,4]])
b

<tf.Tensor: id=5, shape=(12,), dtype=int32, numpy=array([0, 0, 0, 1, 3, 2, 4, 5, 0, 0, 0, 0])>

In [8]:
a =tf.random.uniform([3,4],maxval = 9,dtype = tf.int32)
a

<tf.Tensor: id=9, shape=(3, 4), dtype=int32, numpy=
array([[3, 6, 8, 1],
       [3, 7, 1, 3],
       [7, 2, 0, 5]])>

In [10]:
tf.pad(a,[[2,1],[1,1]])

<tf.Tensor: id=12, shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 3, 6, 8, 1, 0],
       [0, 3, 7, 1, 3, 0],
       [0, 7, 2, 0, 5, 0],
       [0, 0, 0, 0, 0, 0]])>

In [13]:
a = tf.random.normal([4,28,28,3])
b = tf.pad(a,[[0,0],[2,2],[2,2],[0,0]])

In [14]:
b.shape

TensorShape([4, 32, 32, 3])

In [19]:
a = tf.random.uniform([3,4],maxval=4,dtype =tf.int32)
a

<tf.Tensor: id=37, shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 2, 1],
       [0, 0, 3, 1],
       [3, 2, 1, 1]])>

## 2.tile复制，前面分别代表行与列，多维同理

In [20]:
tf.tile(a,[1,2])

<tf.Tensor: id=39, shape=(3, 8), dtype=int32, numpy=
array([[1, 0, 2, 1, 1, 0, 2, 1],
       [0, 0, 3, 1, 0, 0, 3, 1],
       [3, 2, 1, 1, 3, 2, 1, 1]])>

In [22]:
tf.tile(a,[2,1])

<tf.Tensor: id=41, shape=(6, 4), dtype=int32, numpy=
array([[1, 0, 2, 1],
       [0, 0, 3, 1],
       [3, 2, 1, 1],
       [1, 0, 2, 1],
       [0, 0, 3, 1],
       [3, 2, 1, 1]])>