In [2]:
import tensorflow as tf

In [3]:
a = tf.fill([2,2],2.)
a

<tf.Tensor: id=2, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [4]:
b = tf.ones([2,2])
b

<tf.Tensor: id=5, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [5]:
a+b#矩阵加

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [6]:
a-b#矩阵减

<tf.Tensor: id=7, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [7]:
a*b#矩阵乘

<tf.Tensor: id=8, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [8]:
a//b#整除

<tf.Tensor: id=9, shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [9]:
a%b#取余

<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [10]:
a**2#平方

<tf.Tensor: id=12, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [11]:
c=tf.pow(a,3)#pow是乘方的函数形式
c

<tf.Tensor: id=14, shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [12]:
d = tf.sqrt(b)#开方
d

<tf.Tensor: id=15, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [13]:
c = tf.math.log(b)#log运算
c

<tf.Tensor: id=16, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [14]:
d = tf.exp(b)
d

<tf.Tensor: id=17, shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

In [15]:
a @ b

<tf.Tensor: id=18, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [17]:
tf.matmul(a,b)#两者都表示乘法

<tf.Tensor: id=19, shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [18]:
a = tf.ones([2,3,4])
a

<tf.Tensor: id=22, shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [21]:
b = tf.fill([2,4,5],3.)
b

<tf.Tensor: id=25, shape=(2, 4, 5), dtype=float32, numpy=
array([[[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]],

       [[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]]], dtype=float32)>

In [24]:
(a@b).shape#乘法中比较神奇的是，[2,3,4]*[2,4,5]=[2,3,5]，这里前面的2可以理解为bitch，剩下后面的相乘。

TensorShape([2, 3, 5])

In [25]:
a = tf.random.normal([4,3,5])
a.shape

TensorShape([4, 3, 5])

In [35]:
b = tf.random.normal([5,3])
b.shape

TensorShape([5, 3])

In [38]:
b= tf.broadcast_to(b,[4,5,3])#还可以借助broadcast_to来计算乘
(a@b).shape

TensorShape([4, 3, 3])